name: develop pre-merge check

on: 
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

env:
  CMAKE_VERSION: 3.17.2

jobs:
  cmake-build:
    name: cmake build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0, windows-latest, ubuntu-20.04, ubuntu-18.04]
        dotnet: [3.1.x]

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/checkout@v2
    - name: build and test
      if: matrix.os != 'windows-latest'
      run: |
        ./tools/build.sh
        ./tools/test.sh
    - name: build and test on win
      if: matrix.os == 'windows-latest'
      run: |
        ./tools/build_core3.bat
        ./tools/test_core3.bat
