name: sprint pre-merge check

on: 
  push:
    branches:
    - features/sprint*
  pull_request:
    branches:
    - features/sprint*

env:
  CMAKE_VERSION: 3.17.2

jobs:
  cmake-build:
    name: cmake build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0, windows-2019, ubuntu-20.04, ubuntu-18.04]
        dotnet: [3.1.x, 5.0.x]

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/checkout@v2
    - name: build and test on ubuntu
      if: runner.os == 'Linux'
      run: |
        ./tools/build.sh
        ./tools/test.sh
    - name: build and test on mac
      if: runner.os == 'macOS'
      run: |
        ./tools/build.sh
        ./tools/test.sh
    - name: build and test on windows
      if: runner.os == 'Windows'
      run: |
        .\tools\build.bat
        .\tools\test.bat
